name: Build ToolMaker runtime Docker image

on:
  workflow_call:
    inputs:
      arch:
        required: false
        type: string
        default: cpu
      tag:
        required: false
        type: string
        default: cpu

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.ref_name }}-${{ inputs.tag }}
            type=raw,value=${{ github.ref_name }}-${{ inputs.tag }}-${{ github.run_number }}
            type=raw,value=${{ github.ref_name }},enable=${{ inputs.tag == 'cpu' }}
            type=raw,value=${{ inputs.tag }},enable=${{ github.ref_name == 'main' }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/runtime.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ARCH=${{ inputs.arch }}
